### ISSUE TITLE
贵项目使用什么开源协议？

### ISSUE THREAD

**Issue by xqymain** [dl233/OneIndex-theme-nexmoes#1]
最近也在接触Oneindex，看到您的模板很喜欢，希望能修改后加入到自己的[开源项目](https://github.com/xqymain/OneIndexR)里。
现已完成第一个Alpha版本，稍候会上传。

## 3、感谢您对贵项目的付出。

**Comment by dl233** [comment]
首先很高兴你能喜欢这个项目，在原OneIndex删库后也希望能有更多人来维护这个网盘应用，使得环境更加丰富多彩。
称呼我为 dl233&nbsp;就好了，相关开源协议已经添加至项目代码里，可以前往查看&nbsp;LICENSE，允许二次开发和商用。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dl233/OneIndex-theme-nexmoes"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月11日(星期六) 下午2:58
收件人:&nbsp;"dl233/OneIndex-theme-nexmoes"<OneIndex-theme-nexmoes@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[dl233/OneIndex-theme-nexmoes] 贵项目使用什么开源协议？ (#1)





 
最近也在接触Oneindex，看到您的模板很喜欢，希望能修改后加入到自己的开源项目里。
 现已完成第一个Alpha版本，稍候会上传。
 
1、怎么称呼您，介绍您的项目（比如在Readme或者项目内鸣谢）
 
2、使用什么开源协议，是否同意二次开发和商用（本项目并不会商用，若不同意会销毁项目）
 
3、感谢您对贵项目的付出。

**Comment by xqymain** [comment]
正在对项目按照开源协议的要求修改，感谢您能对开源项目理解的态度！那么，谢谢啦~
